In [1]:
import os
#os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'
import torch

In [2]:
t = torch.linspace(0, 1, 5)

In [3]:
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [4]:
T = torch.fft.rfft(t)

In [5]:
T

tensor([ 2.5000+0.0000j, -0.6250+0.8602j, -0.6250+0.2031j])

In [6]:
torch.fft.irfft(T)

tensor([0.1562, 0.3511, 0.7812, 1.2114])

In [7]:
t_mps = torch.linspace(0, 1, 5).to('mps')

In [8]:
t_mps

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000], device='mps:0')

In [9]:
T_mps = torch.fft.rfft(t_mps)

NotImplementedError: The operator 'aten::_fft_r2c' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.